name: TAP_SCHEMA
version: "1.1"
description: A TAP-standard-mandated schema to describe tablesets in a TAP 1.1 service
tables:
- name: "schemas"
  description: description of schemas in this tableset
  primaryKey: "#schemas.schema_name"
  tap:table_index: 100000
  mysql:engine: "InnoDB"
  columns:
  - name: "schema_name"
    datatype: "string"
    description: schema name for reference to tap_schema.schemas
    length: 64
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 1
  - name: "utype"
    datatype: "string"
    description: lists the utypes of schemas in the tableset
    length: 512
    tap:principal: 1
    tap:std: 1
    tap:column_index: 2
  - name: "description"
    datatype: "string"
    description: describes schemas in the tableset
    length: 512
    tap:principal: 1
    tap:std: 1
    tap:column_index: 3
  - name: "schema_index"
    datatype: "int"
    description: recommended sort order when listing schemas
    tap:principal: 1
    tap:std: 1
    tap:column_index: 4
- name: "tables"
  description: description of tables in this tableset
  primaryKey: "#tables.table_name"
  tap:table_index: 101000
  mysql:engine: "InnoDB"
  columns:
  - name: schema_name
    datatype: string
    description: the schema this table belongs to
    length: 64
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 1
  - name: table_name
    datatype: string
    description: the fully qualified table name
    length: 128
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 2
  - name: table_type
    datatype: string
    description: "one of: table view"
    length: 8
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 3
  - name: utype
    datatype: string
    description: lists the utype of tables in the tableset
    length: 512
    tap:principal: 1
    tap:std: 1
    tap:column_index: 4
  - name: description
    datatype: string
    description: describes tables in the tableset
    length: 512
    tap:principal: 1
    tap:std: 1
    tap:column_index: 5
  - name: table_index
    datatype: int
    description: recommended sort order when listing tables
    tap:principal: 1
    tap:std: 1
    tap:column_index: 6
  constraints:
  - name: "k1"
    "@type": ForeignKey
    columns: ["#tables.schema_name"]
    referencedColumns: ["#schemas.schema_name"]
- name: "columns"
  description: description of columns in this tableset
  primaryKey: ["#columns.table_name", "#columns.column_name"]
  tap_table_index: 102000
  mysql:engine: "InnoDB"
  columns:
  - name: table_name
    datatype: string
    description: the table this column belongs to
    length: 128
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 1
  - name: column_name
    datatype: string
    description: the column name
    length: 64
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 2
  - name: utype
    datatype: string
    description: lists the utypes of columns in the tableset
    length: 512
    tap:principal: 1
    tap:std: 1
    tap:column_index: 3
  - name: ucd
    datatype: string
    description: lists the UCDs of columns in the tableset
    length: 64
    tap:principal: 1
    tap:std: 1
    tap:column_index: 4
  - name: unit
    datatype: string
    description: lists the unit used for column values in the tableset
    length: 64
    tap:principal: 1
    tap:std: 1
    tap:column_index: 5
  - name: description
    datatype: string
    description: describes the columns in the tableset
    length: 512
    tap:principal: 1
    tap:std: 1
    tap:column_index: 6
  - name: datatype
    datatype: string
    description: lists the ADQL datatype of columns in the tableset
    length: 64
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 7
  - name: arraysize
    datatype: string
    description: lists the size of variable-length columns in the tableset
    length: 16
    tap:principal: 1
    tap:std: 1
    tap:column_index: 8
  - name: xtype
    datatype: string
    description: a DALI or custom extended type annotation
    length: 64
    tap:principal: 1
    tap:std: 1
    tap:column_index: 9
  - name: size
    datatype: int
    description: "deprecated: use arraysize"
    tap:principal: 1
    tap:std: 1
    tap:column_index: 10
  - name: principal
    datatype: int
    description: a principal column; 1 means 1, 0 means 0
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 11
  - name: indexed
    datatype: int
    description: an indexed column; 1 means 1, 0 means 0
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 12
  - name: std
    datatype: int
    description: a standard column; 1 means 1, 0 means 0
    nullable: false
    tap:principal: 1
    tap:std: 1
    tap:column_index: 13
  - name: column_index
    datatype: int
    description: recommended sort order when listing columns
    tap:principal: 1
    tap:std: 1
    tap:column_index: 14
  constraints:
  - name: "k2"
    "@type": ForeignKey
    columns: ["#columns.table_name"]
    referencedColumns: ["#tables.table_name"]
- name: "keys"
  description: description of foreign keys in this tableset
  primaryKey: "#keys.key_id"
  tap:table_index: 103000
  mysql:engine: "InnoDB"
  columns:
  - name: key_id
    datatype: string
    description: unique key to join to tap_schema.key_columns
    length: 64
    nullable: false
  - name: from_table
    datatype: string
    description: the table with the foreign key
    length: 128
    nullable: false
  - name: target_table
    datatype: string
    description: the table with the primary key
    length: 128
    nullable: false
  - name: utype
    datatype: string
    description: lists the utype of keys in the tableset
    length: 512
  - name: description
    datatype: string
    description: describes keys in the tableset
    length: 512
  constraints:
  - name: "k3"
    "@type": ForeignKey
    columns: ["#keys.from_table"]
    referencedColumns: ["#tables.table_name"]
  - name: "k4"
    "@type": ForeignKey
    columns: ["#keys.target_table"]
    referencedColumns: ["#tables.table_name"]
- name: "key_columns"
  description: description of foreign key columns in this tableset
  tap:table_index: 104000
  mysql:engine: "InnoDB"
  columns:
  - name: key_id
    datatype: string
    length: 64
    nullable: false
  - name: from_column
    datatype: string
    length: 64
    nullable: false
  - name: target_column
    datatype: string
    length: 64
    nullable: false
  constraints:
  - name: "k5"
    "@type": ForeignKey
    columns: ["#key_columns.key_id"]
    referencedColumns: ["#keys.key_id"]
    # FIXME: These can't be defined as FK constraints, because they refer
    # to non-unique columns, e.g., column_name from the columns table.
    # - name: "k6"
    #  "@type": ForeignKey
    #  columns: ["#key_columns.from_column"]
    #  referencedColumns: ["#columns.column_name"]
    # - name: "k7"
    #  "@type": ForeignKey
    #  columns: ["#key_columns.target_column"]
    #  referencedColumns: ["#columns.column_name"]
